### ISSUE TITLE
DeskBuddy Community Project

### ISSUE THREAD

**Issue by jwafu** [pieces-app/opensource#22]
We are currently in the planning phase of this project around developer productivity and creating a simple desktop dashboard that uses PiecesApi's to retrieve, extract, and generate code examples and answers by utilizing context - while providing developers with a clear picture of their efficiencies and improvements on a day by day basis.

Repo: https://github.com/ayothekingg/deskbuddy

#### 20% of the way there ! 
[🟨 🟨 -----------------------] 

#### Current Update 
- [x] See planning issues and leave thoughts and comments.
- [x] Deciding Milestones and complete draft ideas and thoughts 
- [ ] [Project Environment Configuration & Setup](https://github.com/ayothekingg/deskbuddy/milestone/1) 
- [ ] [Backend Development](https://github.com/ayothekingg/deskbuddy/milestone/2)
- [ ] [Frontend UX/UI Development](https://github.com/ayothekingg/deskbuddy/milestone/3)

**Comment by ayothekingg** [comment]
Sounds exciting! Would love to get on this.
