### ISSUE TITLE
GitHub Sync Automation Script

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/opensource#25]
# Overview

We currently have a very manual guide for syncing snippets across multiple devices which can be found [here](https://docs.pieces.app/product-highlights-and-benefits/sync-across-multiple-devices-using-github).

The goal of this project would be to automate this process.

This outline will evolve with the conversations on this issue. 

Original Discord Conversation: https://discord.com/channels/1098986658851999776/1098986660143837209/1193991456046715041

## Terms

- Machine 1: This is the computer with the most recent updates
- Machine 2: This is the computer that you want to pull the latest updates from

## v1 Task

- [ ] Write a script that pushes the changed files on Machine 1 when Pieces OS quits
- [ ] Write a script that pulls on Machine 2

## Requirements

- [ ] This code should be able to run on macOS, Windows, and Linux
  - [ ] This code should utilize the minimum number of dependencies to allow this
- [ ] This code should automate the very manual process of pushing/pulling your Pieces DB from GitHub

## Future Version

Once we get a working version that commits code when Pieces OS quits, then we can evolve the script to automate the syncing process.

**Comment by mason-at-pieces** [comment]
> @mason-at-pieces is this default or a non default feature?

I'm not 100% sure what you mean by default/non-default but this will simply just be a script that users can run on their machines to do this task.

**Comment by HRA42** [comment]
Create a repo for the windows script:
https://github.com/HRA42/Pieces-VCS-Sync-Windows

If anybody is keen to collaborate on this, I'm open to PRs and merge them in asap. On Windows, we should default to using PowerShell 5. Keep in mind that most people don't have PowerShell 7 installed and don't want to install it.

**Comment by jordan-pieces** [comment]
@HRA42 if you want to get a PR up so at least the base file structure and paths are available for others to collaborate on (if they choose to)?

**Comment by HRA42** [comment]
@jordan-pieces It's up in its own branch now.

I hope I can get some initial work (specially on the backup script) done tomorrow.

**Comment by HRA42** [comment]
Needed to refactor me local Git Repo, has some issue with the file system sync, I restored the repo to the correct timeline.

Working now on the backup script. #26

**Comment by mason-at-pieces** [comment]
@HRA42 Going to close this. If we want to continue the convo, we can in our opensource discussions 👍
