### ISSUE TITLE
🟢 Google Summer of Code 2024 Application - SUBMITTED  

### ISSUE THREAD

**Issue by shivay-at-pieces** [pieces-app/opensource#28]
This issue outlines all of the information about the Google Summer of Code participation. 

### 
Pieces is planning on participating in Google Summer of Code 2024 as an organization. 

### Checklist
- [x] Create [Organization Profile](https://docs.google.com/document/d/1mSFc5kb350Jbsan3yLCWIbC4AFF58J67CrJPMTtblKo/edit) on Google Summer of Code Website
    - [x] Org Logo ( Your organization logo must be a PNG, with a minimum height and width of 256 pixels.)
    - [x] Tagline 
    - [x] Primary Open Source License
    - [x] Organization Categories
    - [x] [New Idea List URL](https://docs.google.com/document/d/1FRODQjyhQUyPSmeM3LDxhWC68R1v-rVof_bf6Jw6rTQ/edit) 
    - [x] Org technologies
    - [x] Org topics
    - [x] Org Description
    - [x] Contributor Guidance
    - [x] Comms methods
- [x] Contributor Guidance (for reference: https://unify.ai/docs/ivy/overview/contributing.html) 
- [x] Org Quesstionare
- [x] Idea List Document (for reference: https://docs.google.com/document/d/1pbPx4yc_nACIjV6_UVCy7iLmYJlxPeYx7Oc1DBny8e8/edit) 
- [x] Selection of the current + new project ideas that we need to share in the idea list
- [x] Mission Statements
- [x] Goals

#### Motivation

As part of ongoing efforts to further strengthen open source adoption for Pieces, open source mentorship programs like Google Summer of Code provide a great opportunity to help get potential contributors to come and contribute to open source projects. And it gives a lot of visibility to the organization as a whole. 

1. **Attract New Contributors:** GSoC will help attract new contributors.

2. **Improve Project Documentation:** As part of GSoC, contributors also help improve project documentation, making the project more accessible to new contributors in the future.

3. **Increase Visibility:** Participating in GSoC will help increase the project's visibility in the open-source community. This can attract more users and contributors to the project.

#### Issues + Resources 
- [https://www.youtube.com/watch?v=L4JNz6zWzLs](https://www.youtube.com/watch?v=L4JNz6zWzLs) - Video on Organizations in GSoC

**Comment by jordan-pieces** [comment]
heres where we can start to store any documents: [GSoC folder in Drive](https://drive.google.com/drive/u/0/folders/1SkuxUNZiCJYX2BbdlDrRcKPAf-E7i43h)

**Comment by jordan-pieces** [comment]
Sadly we did not make it in to google summer of code this year but will be trying to get in next year when our programs office is even further along! Also there are some opportunities to join up with other orgs and potentially work with them on their projects, and we my try and take this approach.
