### ISSUE TITLE
Let's put together some technical illustration in the documentation

### ISSUE THREAD

**Issue by seantiz** [pieces-app/opensource#41]
Starting this issue on @jordan-pieces 's suggestion

For the readmes [here](https://www.npmjs.com/package/@pieces.app/pieces-os-client) and for all readmes on the SDK repos, we can start to bring in some graphs as an overview of the patterns we're contributing to.

For example, understanding where pieces-os-client comes in as an abstraction layer on top of OpenAI API, and moving across the graph from there as a starting point. 

I'm happy to get the ball rolling on this as I use Concepts App (vector illustration app) every day, and we can do it in the same style as the Pieces blog graphics if someone can provide the re-usable assets. But I would also need the guidance of a Pieces member who knows the Pieces API endpoints well and how they all work together, from query to training data to discriminator method on the prediction values. 

Here's an example overview graph from neo4j's site

<img width="597" alt="Screenshot 2024-02-13 at 12 57 14" src="https://github.com/pieces-app/opensource/assets/135666428/8bcf7b63-dda5-49e8-9ae4-e820c905bf6d">

**Comment by mason-at-pieces** [comment]
We are actually redo'ing our github readme's for all open source repos like sdks and projects to make them a bit more concise so I am going to close this but if we want to continue this convo, we can in our [open source discussions](https://github.com/pieces-app/opensource/discussions)
