### ISSUE TITLE
Feature Request: Attach Screenshots to Code Snippets

### ISSUE THREAD

**Issue by MrIntellectX** [pieces-app/opensource#54]
I'd like to suggest adding a feature to attach screenshots with code snippets.

As developers, we often deal with numerous similar snippets. Incorporating a visual element, such as screenshots, can help us spot the one we need faster because we process images quicker than text. This would make finding code easier, particularly for frameworks like Flutter and React.

Thank you for considering my request. I look forward to any improvements that make our development process smoother.

<img width="1920" alt="pieces_screenshot_feature" src="https://github.com/pieces-app/opensource/assets/36538038/bc4c7428-d312-45c9-a33c-438c946975b2">

**Comment by mason-at-pieces** [comment]
Hey @MrIntellectX, if you could add this as a discussion on our `Support` repo that would be great as it is more a feature request on our Desktop App 👍 

https://github.com/pieces-app/support/discussions/categories/ideas
