### ISSUE TITLE
Add Svelte x Pieces Project to Community Projects List

### ISSUE THREAD

**Issue by mason-at-pieces** [pieces-app/opensource#57]
@seantiz is creating a Svelte x Pieces project that would be great to add to our Community Projects List on this repos README.

@seantiz if you want to add your project and details around it, that would be great.

**Comment by seantiz** [comment]
Thanks @mason-at-pieces !

The [Svelte x Pieces repo is here](https://github.com/seantiz/piecesvelte) with a documented readme. 

The project is a quick way to setup a copilot chat and make it highly readable on the front-end, using Sveltekit's built-in methods to present your Pieces chat history within a lightweight, easy-to-build interface.

**Comment by mason-at-pieces** [comment]
@seantiz That's great, if you want to fork this and add your project to the README.md file in our community projects list, that would be amazing 👍

**Comment by seantiz** [comment]
> @seantiz That's great, if you want to fork this and add your project to the README.md file in our community projects list, that would be amazing 👍

done! This is great!
